### ISSUE TITLE
reduce package size

### ISSUE THREAD

**Issue by jlengstorf** [domitriusclark/use-cloudinary#17]
I was pulling this in and spotted a few opportunities for decreasing the bundle size that could have a pretty significant impact

https://bundlephobia.com/result?p=use-cloudinary@3.1.6

right now, this package pulls in _all_ of the Cloudinary SDK for every hook, which I don't think (?) is necessary. it also pulls in all of lodash, which I’m almost positive is not necessary

I also think bumping the minimum Node version to 12 ([LTS](https://nodejs.org/en/about/releases/)) would help drop a lot of the polyfill stuff that gets bundled up right now

I also wonder what the impact would be if each hook could be imported separately instead of putting the whole shebang in `index.es.js`?

happy to help with this if you want to pair up or something!

**Comment by domitriusclark** [comment]
Yo @jlengstorf sorry for taking so long to answer here

This was definitely an issue I've been wanting to revisit. Sadly lodash -- in full 0 -- comes with the cloudinary SDK (this will no longer be the case in an upcoming revamp

I'd love to pair up and learn how to shed some extra weight from this though

**Comment by jlengstorf** [comment]
![shrink](https://media.giphy.com/media/5nmkEYKO5n3TYFjQLT/giphy.gif)
