### ISSUE TITLE
Test suites fail 

### ISSUE THREAD

**Issue by calebdeji** [domitriusclark/use-cloudinary#21]
One of the scenerios

    useAudio › updates status to loading when calling getAudio

    TypeError: result.current.getAudio is not a function

      26 |     const { result, waitForNextUpdate } = renderHook(() => useAudio({ cloud_name: "testing-hooks-upload" }));
      27 |     await act(async () => {
    > 28 |       await result.current.getAudio({ public_id: "game-sounds/switch" })
         |                            ^
      29 |       expect(result.current.status).toBe("loading");
      30 |     });
      31 | 
`

Seems the tests were written for the older version.  useAudio hook doesn't return getAudio variable and status variable 

![use-cloudinary](https://user-images.githubusercontent.com/33372799/93642180-8b718d80-f9f5-11ea-8474-0931d0d8fa72.png)

Would like to raise a PR concerning this issue.

**Comment by calebdeji** [comment]
PR created

https://github.com/domitriusclark/use-cloudinary/pull/22

**Comment by domitriusclark** [comment]
Thank you @calebdeji will check out your PR ASAP !!
